site_name: Volterra Dry Lab Guide
theme: cinder
site_author: vivar
repo_url: "https://wwwfbm.unil.ch/dnf/group/glia-an-active-synaptic-partner/member/volterra-andrea-volterra"
use_directory_urls: false
site_description: Documentation of Volterra Lab
copyright: "This documentation is for exclusive use of Volterra Laboratory members use at DNF-UNIL. In case you find useful for others labs and you want to share first contact carlos.vivarrios@unil.ch"
pages:
    - Home: index.md
    - "Computing": servers.md
    - "Software": software.md
    - "LS Analysis": Linescan_analysis.md
    - "F.A.Q.": faq.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
